spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
jwt:
  secret: testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest
server:
  servlet:
    encoding:
      charset: UTF-8