spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
server:
  ssl:
    key-store: /home/ubuntu/kinder-back/deploy/
    key-store-type: PKCS12
    key-store-password: kinderkinder123
    enabled: true
    key-alias: tomcat

  servlet:
    encoding:
      charset: UTF-8
  port: 8443