spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:tcp://localhost/~/kinder
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    show-sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
logging:
  level:
    root: info