spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  cache:
    type: redis
server:
  servlet:
    encoding:
      charset: UTF-8
  port: 443
  ssl:
    key-store: classpath:keystore.p12
    key-store-type: PKCS12
    key-store-password: Rhrhtl45!11
    enabled: true